/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Dialog;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Nicholas.Sixbury
 */
public class ImageFormatDialog extends javax.swing.JDialog {

	DefaultListModel<String> model = new DefaultListModel<>();
	DefaultComboBoxModel<String> combo = new DefaultComboBoxModel<>();

	/**
	 * Creates new form ImageTypeDialog
	 */
	public ImageFormatDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		FlatLightLaf.setup();
		initComponents();
		uxSupportedFormatsList.setModel(model);
		uxFormatMenu.setModel(combo);

		// set up initial accessible image format options
		combo.addElement("BMP");
		combo.addElement("PNG");
		combo.addElement("TIFF");
		combo.addElement("Multi-TIFF");
	}

	public int image_format_code = 7;
	public List<String> supported_image_formats = new ArrayList<>();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uxFormatMenu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uxSupportedFormatsList = new javax.swing.JList<>();
        uxCancelBtn = new javax.swing.JButton();
        uxConfirmBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Scanned Image Format/Extension");

        uxFormatMenu.setFont(uxFormatMenu.getFont().deriveFont(uxFormatMenu.getFont().getSize()+2f));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Image Format");

        uxSupportedFormatsList.setFont(uxSupportedFormatsList.getFont().deriveFont(uxSupportedFormatsList.getFont().getSize()+2f));
        jScrollPane1.setViewportView(uxSupportedFormatsList);

        uxCancelBtn.setFont(uxCancelBtn.getFont().deriveFont(uxCancelBtn.getFont().getSize()+2f));
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        uxConfirmBtn.setFont(uxConfirmBtn.getFont().deriveFont(uxConfirmBtn.getFont().getSize()+2f));
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supported Image Formats:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxFormatMenu, 0, 106, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uxFormatMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates interface based on public vars
	 */
	public void updateInterface() {
		if (image_format_code == 0) {combo.setSelectedItem("TIFF");}
		else if (image_format_code == 2) {combo.setSelectedItem("BMP");}
		else if (image_format_code == 6) {combo.setSelectedItem("Multi-TIFF");}
		else if (image_format_code == 7) {combo.setSelectedItem("PNG");}
		else {combo.setSelectedItem("TIFF");}
		model.clear();
		for (String string : supported_image_formats) {
			model.addElement(string);
		}//end adding each supported format to the list
	}//end updateInterface()

	@Override
	public void setVisible(boolean visibility) {
		updateInterface();
		super.setVisible(visibility);
	}//end setVisible(visibility)

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        this.setVisible(false);
		/**
		 * For some reason, the selected item is only updated when set
		 * programmatically, not when the user selects something.
		 * I cannot fathom why this behavior would be default and
		 * difficult to change.
		 */
		System.out.println(uxFormatMenu.getSelectedItem());
		System.out.println(uxFormatMenu.getSelectedIndex());
		System.out.println(combo.getSelectedItem());
		if (combo.getSelectedItem() == "TIFF") {image_format_code = 0;}
		else if (combo.getSelectedItem() == "BMP") {image_format_code = 2;}
		else if (combo.getSelectedItem() == "Multi-TIFF") {image_format_code = 6;}
		else if (combo.getSelectedItem() == "PNG") {image_format_code = 7;}
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JComboBox<String> uxFormatMenu;
    private javax.swing.JList<String> uxSupportedFormatsList;
    // End of variables declaration//GEN-END:variables
}
