/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Dialog;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Nicholas.Sixbury
 */
public class NumSuffixDialog extends javax.swing.JDialog {

	/**
	 * Creates new form NumSuffixDialog
	 */
	public NumSuffixDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		FlatLightLaf.setup();
		initComponents();
	}

	public boolean num_suffix_enabled = true;
	public int num_suffix_min_digits = 2;
	public int num_suffix_start_num = 1;
	public int num_suffix_cur_num = 1;
	public int num_suffix_increment = 1;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uxEnableNumberSuffixChck = new javax.swing.JCheckBox();
        uxNumberSuffixSettingsPanel = new javax.swing.JPanel();
        uxMinDigitsSpnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        uxNumSuffixCurrentSpnr = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uxExampleDisplay = new javax.swing.JLabel();
        uxNumSuffixStartSpnr = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        uxNumSuffixIncrementSpnr = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        uxCancelBtn = new javax.swing.JButton();
        uxConfirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Number Suffix Settings");

        uxEnableNumberSuffixChck.setFont(uxEnableNumberSuffixChck.getFont().deriveFont(uxEnableNumberSuffixChck.getFont().getSize()+2f));
        uxEnableNumberSuffixChck.setText("Enable Number Suffix");
        uxEnableNumberSuffixChck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxEnableNumberSuffixChckActionPerformed(evt);
            }
        });

        uxNumberSuffixSettingsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uxMinDigitsSpnr.setFont(uxMinDigitsSpnr.getFont().deriveFont(uxMinDigitsSpnr.getFont().getSize()+2f));
        uxMinDigitsSpnr.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));
        uxMinDigitsSpnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                uxMinDigitsSpnrStateChanged(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Min Digits in Suffix");

        uxNumSuffixCurrentSpnr.setFont(uxNumSuffixCurrentSpnr.getFont().deriveFont(uxNumSuffixCurrentSpnr.getFont().getSize()+2f));
        uxNumSuffixCurrentSpnr.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        uxNumSuffixCurrentSpnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                uxNumSuffixCurrentSpnrStateChanged(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Start At");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+2f));
        jLabel3.setText("Current Setting:");

        uxExampleDisplay.setFont(uxExampleDisplay.getFont().deriveFont(uxExampleDisplay.getFont().getSize()+2f));
        uxExampleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uxExampleDisplay.setText("imagename01");
        uxExampleDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uxNumSuffixStartSpnr.setFont(uxNumSuffixStartSpnr.getFont().deriveFont(uxNumSuffixStartSpnr.getFont().getSize()+2f));
        uxNumSuffixStartSpnr.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+2f));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Current Number");

        uxNumSuffixIncrementSpnr.setFont(uxNumSuffixIncrementSpnr.getFont().deriveFont(uxNumSuffixIncrementSpnr.getFont().getSize()+2f));
        uxNumSuffixIncrementSpnr.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+2f));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Increment");

        javax.swing.GroupLayout uxNumberSuffixSettingsPanelLayout = new javax.swing.GroupLayout(uxNumberSuffixSettingsPanel);
        uxNumberSuffixSettingsPanel.setLayout(uxNumberSuffixSettingsPanelLayout);
        uxNumberSuffixSettingsPanelLayout.setHorizontalGroup(
            uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uxNumberSuffixSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uxNumberSuffixSettingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxExampleDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(uxNumberSuffixSettingsPanelLayout.createSequentialGroup()
                        .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uxNumSuffixIncrementSpnr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uxNumSuffixCurrentSpnr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uxMinDigitsSpnr)
                            .addComponent(uxNumSuffixStartSpnr))))
                .addContainerGap())
        );
        uxNumberSuffixSettingsPanelLayout.setVerticalGroup(
            uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uxNumberSuffixSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(uxMinDigitsSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uxNumSuffixStartSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxNumSuffixCurrentSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxNumSuffixIncrementSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uxNumberSuffixSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uxNumberSuffixSettingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(uxExampleDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        uxCancelBtn.setFont(uxCancelBtn.getFont().deriveFont(uxCancelBtn.getFont().getSize()+2f));
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        uxConfirmBtn.setFont(uxConfirmBtn.getFont().deriveFont(uxConfirmBtn.getFont().getSize()+2f));
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uxNumberSuffixSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uxEnableNumberSuffixChck)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uxEnableNumberSuffixChck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uxNumberSuffixSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Updates interface based on public vars
	 */
	public void updateInterface() {
		this.uxEnableNumberSuffixChck.setSelected(num_suffix_enabled);
		setPanelEnabled(num_suffix_enabled);
		this.uxMinDigitsSpnr.setValue(num_suffix_min_digits);
		this.uxNumSuffixStartSpnr.setValue(num_suffix_start_num);
		this.uxNumSuffixCurrentSpnr.setValue(num_suffix_cur_num);
		this.uxNumSuffixIncrementSpnr.setValue(num_suffix_increment);
		uxExampleDisplay.setText(generateExampleText());
	}//end updateInterface()

	/**
	 * Generates a string based on public vars to serve as an
	 * example of how the current number suffix format works.
	 */
	public String generateExampleText() {
		num_suffix_cur_num = (int) uxNumSuffixCurrentSpnr.getValue();
		num_suffix_min_digits = (int) uxMinDigitsSpnr.getValue();
		String prefix = "image-name";
		String number = "" + num_suffix_cur_num;
		StringBuilder extra_digits = new StringBuilder();
		while (number.length() + extra_digits.length() < num_suffix_min_digits) {
			extra_digits.append(0);
		}
		return prefix + extra_digits.toString() + number;
	}//end generateExampleText()

	@Override
	public void setVisible(boolean visibility) {
		updateInterface();
		super.setVisible(visibility);
	}//end setVisible(visibility)

	public void setPanelEnabled(boolean enabled) {
		jLabel1.setEnabled(enabled);
		jLabel2.setEnabled(enabled);
		jLabel3.setEnabled(enabled);
		jLabel4.setEnabled(enabled);
		jLabel5.setEnabled(enabled);
		uxExampleDisplay.setEnabled(enabled);
		uxMinDigitsSpnr.setEnabled(enabled);
		uxNumSuffixCurrentSpnr.setEnabled(enabled);
		uxNumSuffixIncrementSpnr.setEnabled(enabled);
		uxNumSuffixStartSpnr.setEnabled(enabled);
		uxNumberSuffixSettingsPanel.setEnabled(enabled);
	}

    private void uxEnableNumberSuffixChckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxEnableNumberSuffixChckActionPerformed
        setPanelEnabled(uxEnableNumberSuffixChck.isSelected());
    }//GEN-LAST:event_uxEnableNumberSuffixChckActionPerformed

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        this.num_suffix_enabled = uxEnableNumberSuffixChck.isSelected();
		this.num_suffix_min_digits = (int) uxMinDigitsSpnr.getValue();
		this.num_suffix_start_num = (int) uxNumSuffixStartSpnr.getValue();
		this.num_suffix_cur_num = (int) uxNumSuffixCurrentSpnr.getValue();
		this.num_suffix_increment = (int) uxNumSuffixIncrementSpnr.getValue();
		this.setVisible(false);
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    private void uxMinDigitsSpnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_uxMinDigitsSpnrStateChanged
        uxExampleDisplay.setText(generateExampleText());
    }//GEN-LAST:event_uxMinDigitsSpnrStateChanged

    private void uxNumSuffixCurrentSpnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_uxNumSuffixCurrentSpnrStateChanged
        uxExampleDisplay.setText(generateExampleText());
    }//GEN-LAST:event_uxNumSuffixCurrentSpnrStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JCheckBox uxEnableNumberSuffixChck;
    private javax.swing.JLabel uxExampleDisplay;
    private javax.swing.JSpinner uxMinDigitsSpnr;
    private javax.swing.JSpinner uxNumSuffixCurrentSpnr;
    private javax.swing.JSpinner uxNumSuffixIncrementSpnr;
    private javax.swing.JSpinner uxNumSuffixStartSpnr;
    private javax.swing.JPanel uxNumberSuffixSettingsPanel;
    // End of variables declaration//GEN-END:variables
}
