/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Nicholas.Sixbury
 */
public class ScanAreaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ScanAreaDialog
     */
    public ScanAreaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        FlatLightLaf.setup();
        initComponents();
    }

    public double X1 = 1.05;
    public double Y1 = 8.89;
    public double X2 = 3.05;
    public double Y2 = 10.89;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uxX1Spnr = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uxY1Spnr = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        uxX2Spnr = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        uxY2Spnr = new javax.swing.JSpinner();
        uxCancelBtn = new javax.swing.JButton();
        uxConfirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Scan Area");

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setText("Coordinates of upper left corner of scan area in inches");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setText("Coordinates of lower right corner of scan area in inches");

        uxX1Spnr.setFont(uxX1Spnr.getFont().deriveFont(uxX1Spnr.getFont().getSize()+2f));
        uxX1Spnr.setModel(new javax.swing.SpinnerNumberModel(1.05d, 0.01d, 100.0d, 0.01d));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+2f));
        jLabel3.setLabelFor(uxX1Spnr);
        jLabel3.setText("X:");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+2f));
        jLabel4.setLabelFor(uxY1Spnr);
        jLabel4.setText("Y:");

        uxY1Spnr.setFont(uxY1Spnr.getFont().deriveFont(uxY1Spnr.getFont().getSize()+2f));
        uxY1Spnr.setModel(new javax.swing.SpinnerNumberModel(8.98d, 0.01d, 100.0d, 0.01d));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+2f));
        jLabel5.setLabelFor(uxX2Spnr);
        jLabel5.setText("X:");

        uxX2Spnr.setFont(uxX2Spnr.getFont().deriveFont(uxX2Spnr.getFont().getSize()+2f));
        uxX2Spnr.setModel(new javax.swing.SpinnerNumberModel(3.05d, 0.01d, 100.0d, 0.01d));

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+2f));
        jLabel6.setLabelFor(uxY2Spnr);
        jLabel6.setText("Y:");

        uxY2Spnr.setFont(uxY2Spnr.getFont().deriveFont(uxY2Spnr.getFont().getSize()+2f));
        uxY2Spnr.setModel(new javax.swing.SpinnerNumberModel(10.98d, 0.01d, 100.0d, 0.01d));

        uxCancelBtn.setFont(uxCancelBtn.getFont().deriveFont(uxCancelBtn.getFont().getSize()+2f));
        uxCancelBtn.setText("Cancel");
        uxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxCancelBtnActionPerformed(evt);
            }
        });

        uxConfirmBtn.setFont(uxConfirmBtn.getFont().deriveFont(uxConfirmBtn.getFont().getSize()+2f));
        uxConfirmBtn.setText("Confirm");
        uxConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uxConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxX1Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uxY1Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uxX2Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uxY2Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(uxCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(uxConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxX1Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(uxY1Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(uxX2Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(uxY2Spnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uxConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updates interface based on public vars
     */
    public void updateInterface() {
        this.uxX1Spnr.setValue(X1);
        this.uxY1Spnr.setValue(Y1);
        this.uxX2Spnr.setValue(X2);
        this.uxY2Spnr.setValue(Y2);
    }//end updateInterface()

    @Override
    public void setVisible(boolean visibility) {
        updateInterface();
        super.setVisible(visibility);
    }//end setVisible(visibility)

    private void uxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxCancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_uxCancelBtnActionPerformed

    private void uxConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uxConfirmBtnActionPerformed
        this.X1 = (double)this.uxX1Spnr.getValue();
        this.Y1 = (double)this.uxY1Spnr.getValue();
        this.X2 = (double)this.uxX2Spnr.getValue();
        this.Y2 = (double)this.uxY2Spnr.getValue();
        this.setVisible(false);
    }//GEN-LAST:event_uxConfirmBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton uxCancelBtn;
    private javax.swing.JButton uxConfirmBtn;
    private javax.swing.JSpinner uxX1Spnr;
    private javax.swing.JSpinner uxX2Spnr;
    private javax.swing.JSpinner uxY1Spnr;
    private javax.swing.JSpinner uxY2Spnr;
    // End of variables declaration//GEN-END:variables
}
